### ISSUE TITLE
关于Mamba计算的问题

### ISSUE THREAD

**Issue by CV-ZhangXin** [walking-shadow/Official_Remote_Sensing_Mamba#1]
作者你好，最近也在看关于Mamba的相关理论，看了些代码但是不太懂Mamba是怎么处理图片的。我看到你的方法分成了多个方向进行扫描。每个扫描的方向，比如（1，2，3，4，5，6，7，8，9）这个方向，是代表将图片分为9块，每个块就代表一个Token Xi吗？让后9个块进行SSM计算。可以这样理解吗？

**Comment by CV-ZhangXin** [comment]
@walking-shadow 可以的话，能解答我的这个问题吗？非常感谢

**Comment by walking-shadow** [comment]
SSM和Mamba的相关理论解析可以看这两篇知乎文章，我感觉帮助挺大的
https://www.zhihu.com/question/644981909/answer/3401898757
https://www.zhihu.com/question/644981978/answer/3405813530

扫描方向你理解的没什么问题，不过实际上块的大小是特定的，图上面画9个块只是为了方便展示

**Comment by CV-ZhangXin** [comment]
@walking-shadow 好的，非常感谢你。

**Comment by CV-ZhangXin** [comment]
@walking-shadow  大佬可以教教我mamba的运算吗，mamba结构看懂了一点。你是不是做了很多方向的Mamba运算，然后最后相加起来了。每个mamba的序列长度为H*W，如果不进行时变的SSM，那么是不是就是有H*W这样一个长度的一个核（当成卷积运算）。

**Comment by walking-shadow** [comment]
Mamba和SSM你可以参照我上面给你的两个知乎回答，视觉图像里的Mamba你可以去看VMamba文章，我是在它的基础上做的工作。
各个方向独立的经过SSM计算之后，是最终加在一起了的。
从卷积的视角来看，可以大体看作是在序列左边进行padding，然后用HW长度的卷积核从左到右进行并行的卷积，但是实际上的处理过程存在一定的差异

**Comment by CV-ZhangXin** [comment]
经过你的解答，我懂了，谢谢您大佬。你的想法很优秀，斜方向和逆回去的代码让我受益良多，祝你论文早日有个好结果，再次谢谢大佬。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "walking-shadow/Official_Remote_Sensing_Mamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月31日(星期天) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [walking-shadow/Official_Remote_Sensing_Mamba] 关于Mamba计算的问题 (Issue #1)





 
Mamba和SSM你可以参照我上面给你的两个知乎回答，视觉图像里的Mamba你可以去看VMamba文章，我是在它的基础上做的工作。
 各个方向独立的经过SSM计算之后，是最终加在一起了的。
 从卷积的视角来看，可以大体看作是在序列左边进行padding，然后用HW长度的卷积核从左到右进行并行的卷积，但是实际上的处理过程存在一定的差异
