### ISSUE TITLE
最低需要什么配置才能跑起来？

### ISSUE THREAD

**Issue by gisbenweil** [walking-shadow/Official_Remote_Sensing_Mamba#10]
如题

**Comment by walking-shadow** [comment]
一般16G就可以了，如果超过显存了，你也可以减小网络的通道数量和第三个阶段的网络层数，从而使用一个更小的网络。我们的RSM使用的是非常简单的网络架构，目的是为了证明SSM-based模型在遥感密集预测任务中的潜力，你完全可以按照你自己的需求进行更改

**Comment by IronmanVsThanos** [comment]
> 减小网络的通道数量和第三个阶段的网络层数

这两个在哪里减少呢？由什么参数控制吗？
