### ISSUE TITLE
What is the minimum memory requirement for training code, as your paper states that it was trained with A100 memory 40GB?

### ISSUE THREAD

**Issue by Krystal9999** [walking-shadow/Official_Remote_Sensing_Mamba#11]

**Comment by walking-shadow** [comment]
Generally, 16GB is sufficient for the experiment. If you exceed the memory, you can also reduce the number of channels in the network and the number of layers in the third stage, thus using a smaller network. Our RSM adopts a very simple network architecture, aiming to demonstrate the potential of SSM-based models in dense remote sensing prediction tasks. You are completely free to make changes according to your own requirements.

**Comment by LPeng625** [comment]
> Generally, 16GB is sufficient for the experiment. If you exceed the memory, you can also reduce the number of channels in the network and the number of layers in the third stage, thus using a smaller network. Our RSM adopts a very simple network architecture, aiming to demonstrate the potential of SSM-based models in dense remote sensing prediction tasks. You are completely free to make changes according to your own requirements.

您好，在Massachusetts Road数据集中，我发现减少网络的dims（96->24），bs=1，在250个epoch能收敛，但是f1最高是76.18，跟paper中80.49还有相当多差距。看来dims对于实际效果影响很大。

**Comment by Krystal9999** [comment]
感谢你的分享，最近我在复现的时候发现，代码里面的这个VSS block，我只发现了Layernorm、OSSM块、mlp，并没有流程图中的DWconv和linear，这是因为什么问题呢？&nbsp;


_Top&nbsp;&#39;刺眼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月28日(星期天) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: "_Top ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [walking-shadow/Official_Remote_Sensing_Mamba] What is the minimum memory requirement for training code, as your paper states that it was trained with A100 memory 40GB? (Issue #11)














  
Generally, 16GB is sufficient for the experiment. If you exceed the memory, you can also reduce the number of channels in the network and the number of layers in the third stage, thus using a smaller network. Our RSM adopts a very simple network architecture, aiming to demonstrate the potential of SSM-based models in dense remote sensing prediction tasks. You are completely free to make changes according to your own requirements.
  
您好，在Massachusetts Road数据集中，我发现减少网络的dims（96-&gt;24），bs=1，在250个epoch能收敛，但是f1最高是76.18，跟paper中80.49还有相当多差距。看来dims对于实际效果影响很大。
