### ISSUE TITLE
Consultation on issues with selective_scan_cuda_oflex and other libraries

### ISSUE THREAD

**Issue by zhouyiqingzz** [walking-shadow/Official_Remote_Sensing_Mamba#15]
Where can I download libraries selective_scan_cuda_oflex, selective_scan_cuda_core and selective_scan_cuda?

**Comment by walking-shadow** [comment]
These libraries belong to the environment of VMamba, you can install them by following the instructions in [VMamba](https://github.com/MzeroMiko/VMamba).
