### ISSUE TITLE
tuple object is not callable

### ISSUE THREAD

**Issue by IronmanVsThanos** [walking-shadow/Official_Remote_Sensing_Mamba#16]
当执行训练脚本出现
![Uploading JWR5{VV6S)ULO}TOB`%T161.png…]()

**Comment by IronmanVsThanos** [comment]
![JWR5{VV6S)ULO}TOB`%T161](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/80081631/d22628f3-1ba4-41c1-ab36-61b6f84d1882)

**Comment by FeatherWaves666** [comment]
同样的问题

**Comment by IronmanVsThanos** [comment]
> 同样的问题

你是不是也取消了下采样版本和patch_embeded 的版本信息？

**Comment by FeatherWaves666** [comment]
> > 同样的问题
> 
> 你是不是也取消了下采样版本和patch_embeded 的版本信息？

是的，但是不取消也会报错

**Comment by IronmanVsThanos** [comment]
> > > 同样的问题
> > 
> > 
> > 你是不是也取消了下采样版本和patch_embeded 的版本信息？
> 
> 是的，但是不取消也会报错

一模一样。。

**Comment by IronmanVsThanos** [comment]
@walking-shadow 作者您好，能帮我们看看问题吗？

**Comment by IronmanVsThanos** [comment]
fine，I slove this

**Comment by IronmanVsThanos** [comment]
OK 代码的问题 解决了

**Comment by FeatherWaves666** [comment]
> OK 代码的问题 解决了

怎么解决的嘞

**Comment by FeatherWaves666** [comment]
已解决：        
```
_make_patch_embed = self._make_patch_embed_v2，
```
去除掉逗号，这里的逗号使得_make_patch_embed变成了一个只包含一个函数的元组，而不是直接将函数本身赋值给_make_patch_embed。

可以close啦

**Comment by IronmanVsThanos** [comment]
> 已解决：
> 
> ```
> _make_patch_embed = self._make_patch_embed_v2，
> ```
> 
> 去除掉逗号，这里的逗号使得_make_patch_embed变成了一个只包含一个函数的元组，而不是直接将函数本身赋值给_make_patch_embed。
> 
> 可以close啦

一样的思路，我实在报错的那里把元组[0]拿出来，其实是一样的。

**Comment by walking-shadow** [comment]
感谢指出错误和提出解决方案，我修改一下仓库中的代码
