### ISSUE TITLE
shape mismatch during inference

### ISSUE THREAD

**Issue by LPeng625** [walking-shadow/Official_Remote_Sensing_Mamba#19]
<img width="1146" alt="image" src="https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/25023673/faad4b79-c4f3-4769-b203-b3f030207d4d">

**Comment by LPeng625** [comment]
Hello, author, what is the cause of this situation, thank you!

**Comment by LPeng625** [comment]
en.shape 1500/4=[..,375,..], de.shape=[..,376,..] How do you deal with the road data set with size 1500 during the test, thank you

**Comment by LPeng625** [comment]
The paper said that cutting the size of the 1500 into 1024, does it mean that a picture is cut into 4, thank you

**Comment by MUSTfitC60** [comment]
Hello! I have encountered the same problem. Have you resolved it?

**Comment by walking-shadow** [comment]
We crop the all the images of 1500×1500 size in Massachusetts Roads Dataset into 1024 × 1024 size, therefore the shape issue would't occur.

**Comment by LPeng625** [comment]
> We crop the all the images of 1500×1500 size in Massachusetts Roads Dataset into 1024 × 1024 size, therefore the shape issue would't occur.

Excuse me, is a 1500 picture cut into 4 1024 pictures?

**Comment by walking-shadow** [comment]
> > We crop the all the images of 1500×1500 size in Massachusetts Roads Dataset into 1024 × 1024 size, therefore the shape issue would't occur.
> 
> Excuse me, is a 1500 picture cut into 4 1024 pictures?

Yes, each image of 1500×1500 size is cropped into 4 images of 1024×1024 size with 548 overlap.

**Comment by LPeng625** [comment]
> > > We crop the all the images of 1500×1500 size in Massachusetts Roads Dataset into 1024 × 1024 size, therefore the shape issue would't occur.
> > 
> > 
> > Excuse me, is a 1500 picture cut into 4 1024 pictures?
> 
> Yes, each image of 1500×1500 size is cropped into 4 images of 1024×1024 size with 548 overlap.

Thank you, the problem has been solved.
