### ISSUE TITLE
about  diagonal_gather and   antidiagonal_gather

### ISSUE THREAD

**Issue by Nevaeh7** [walking-shadow/Official_Remote_Sensing_Mamba#20]
![image](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/70443453/037225bf-136b-4e91-8db9-5cea85b8aedd)
![image](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/70443453/12a71f67-7713-4e82-902e-036b75cfed7e)
Above are the results of the test scans, which don't seem to match the description in the paper

**Comment by walking-shadow** [comment]
Selective scanning in both diagonal and antidiagonal directions is correct in terms of orientation, only the starting position of selective scanning is not fixed, which doesn't affect the effectiveness of selective scanning.
