### ISSUE TITLE
About Run Ablation Experiment

### ISSUE THREAD

**Issue by LPeng625** [walking-shadow/Official_Remote_Sensing_Mamba#21]
Hello, thank you for your excellent work. I would like to ask how to run the ablation experiments of SS1D and SS2D, and how to configure and change the code, thank you!

**Comment by Sanctuary345** [comment]
May I ask how you resolved this?

**Comment by walking-shadow** [comment]
You can check the code for RSM-SS and RSM-CD, and modify the selective scanning direction of OSSM in order to conduct ablation experiments to validate the effectiveness of OSSM.
