### ISSUE TITLE
关于斜向扫描的像素顺序问题

### ISSUE THREAD

**Issue by Seeker98** [walking-shadow/Official_Remote_Sensing_Mamba#23]
老师您好，阅读代码中使用gather和scatter实现斜向扫描的代码后大为震撼，学到许多，但是深入分析发现似乎这样的处理方式使得像素在某种意义上被“打乱”了，实际上拼接起来的并不是严格从左上到右下（其他方向亦然）的像素顺序。想请问一下这是为了高效计算所采用的妥协方式吗？效果是否会因为这种妥协而有一定程度的折扣？

**Comment by walking-shadow** [comment]
SSM的选择性扫描能够起到一定的位置编码的作用，因为它的扫描是单向的，前面的像素无法关注到后面像素的信息，因此选择性扫描之后每一行像素的排列关系并不重要，重要的是选择性扫描的方向。并且把一张图像展平呈一个一维向量时，无论如何都是无法严格保证像素在二维图像中的邻域性的，所以怎么排列都会有种看上去被“打乱”的感觉

**Comment by Seeker98** [comment]
解答来的很及时很详尽，感谢老师！
