### ISSUE TITLE
OSError: image file is truncated (3440 bytes not processed)

### ISSUE THREAD

**Issue by Wupretred** [walking-shadow/Official_Remote_Sensing_Mamba#26]
Hello, I apologize for disturbing you. When I run the train.py file using CUDA 12.1, GCC 11.2, and PyTorch 2.2.2, I encounter an error: "OSError: image file is truncated (3440 bytes not processed)." Have you ever come across this situation before? Or do you know how to resolve this issue?

**Comment by Wupretred** [comment]
![{2C18AF84-6E03-4095-B12E-AB2353362221}](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/49277671/efd1db5b-b73d-4ebd-aec7-f9d854172a67)

**Comment by walking-shadow** [comment]
I haven't encountered this issue before, but based on my search online, the error might occur because your input image is too large. You can try adding the following code to resolve this issue:

```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

**Comment by Wupretred** [comment]
Thank you for your explanation. I am using the Massachusetts dataset. The current hyperparameters are the same as the ones you have made public, and most of the graphs are fine. Do I need to make any changes to the settings?
