### ISSUE TITLE
out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, None, delta_bias, delta_softplus)

### ISSUE THREAD

**Issue by AliasChenYi** [walking-shadow/Official_Remote_Sensing_Mamba#29]
![image](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/91005746/33f0f8fc-b0a1-4080-a8d4-39c2fedf484f)

**Comment by xiaoshenxiangxuexi** [comment]
How did you solve this problem?： Name ‘selective_scan_cuda_core’ is not defined. Do you mean selective_scan_cuda'?

**Comment by walking-shadow** [comment]
You can refer to https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/issues/8

**Comment by keep123ing** [comment]
> Name ‘selective_scan_cuda_core’ is not defined.

请问您解决了吗？
