### ISSUE TITLE
关于选择性扫描方法的选取

### ISSUE THREAD

**Issue by chenzean** [walking-shadow/Official_Remote_Sensing_Mamba#30]
作者，你好：
我看你最终选择扫描使用了SelectiveScanMamba，我想问一下SelectiveScanOflex是否可以实现类似的效果。因为我感觉SelectiveScanOflex的运行速度更快。

**Comment by walking-shadow** [comment]
我们遵循VMamba的默认设置使用了SelectiveScanMamba，如果SelectiveScanOflex的运行速度更快，当然可以使用它来进行选择性扫描
