### ISSUE TITLE
have selective_scan_cuda_core, but no selective_scan_cuda_oflex

### ISSUE THREAD

**Issue by AliasChenYi** [walking-shadow/Official_Remote_Sensing_Mamba#31]
Dear author hello, I want to borrow your code, one of my current situation is to have selective_scan_cuda_core, but no selective_scan_cuda_oflex, I searched the solution, but still can not solve, so I would like to ask you how to solve before, Can you help me? Thank you very much！
![image](https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/assets/91005746/324be2e7-bdfe-435a-8513-d199cea829b0)

**Comment by xiaoshenxiangxuexi** [comment]
Excuse me, have you solved the problem?

**Comment by walking-shadow** [comment]
You can refer to https://github.com/walking-shadow/Official_Remote_Sensing_Mamba/issues/28
