### ISSUE TITLE
train f1score: 0.0 train epoch loss: nan

### ISSUE THREAD

**Issue by rzzzc** [walking-shadow/Official_Remote_Sensing_Mamba#33]
When I trained with my own dataset, the F1 score equaled 1 within a few epochs, and the loss approached 0. After more epochs, the situation of "train f1score: 0.0; train epoch loss: nan" occurred. Do you have any good suggestions? Thank you.

**Comment by Hmbb0606** [comment]
I encountered a similar problem. During a certain epoch of training, I encountered loss=nan. How did you solve it at that time？

**Comment by Assioncreed** [comment]
> 我遇到了类似的问题。在某个 epoch 的训练中，我遇到了 loss=nan。你当时是怎么解决的？
I also have thie problem,did you solve it?
