### ISSUE TITLE
关于遥感任务

### ISSUE THREAD

**Issue by 2225686820** [walking-shadow/Official_Remote_Sensing_Mamba#5]
请问有想过在dota和PANDA这类数据集上测试模型在目标检测方面的性能吗？

**Comment by walking-shadow** [comment]
我们这篇文章主要是为了探究和证明SSM-based模型在超高分辨率遥感密集预测任务上的潜力，而目标检测任务可能并不需要超高分辨率的遥感图像，它们可能更加针对小目标检测等应用。因此在目标检测任务中，大的超高分辨率遥感图像是否必要值得考虑，如果有必要的话，全局上下文信息对于目标检测任务的必要性也需要实验来证明。
目前我们没有考虑在目标检测任务上进行实验，希望其他研究人员可以来进一步探索SSM-based模型在遥感中的各种任务中的潜力。
