### ISSUE TITLE
论文里说实验用的是一张A100，实际运行占用的显存是多少g啊，把A100吃满了吗

### ISSUE THREAD

**Issue by NYB-AAA** [walking-shadow/Official_Remote_Sensing_Mamba#7]

**Comment by walking-shadow** [comment]
看不同的数据集的图像大小了，A100是显存是80G，变化检测实验里面跑2048×2048大小的图片，batch_size设置为1就基本吃满显存了。不过变化检测里模型效果最好的图像大小是1024，所以batch size可以设置为4
