### ISSUE TITLE
NameError: name 'selective_scan_cuda_core' is not defined. Did you mean: 'selective_scan_flop_jit'?

### ISSUE THREAD

**Issue by cyc1111111111** [walking-shadow/Official_Remote_Sensing_Mamba#8]
Hello, I encountered this problem in Windows environment, how to solve it? thank you

**Comment by walking-shadow** [comment]
This package belongs to the VMamba environment, you need to go through the VMamba project environment installation tutorial to ensure that its environment installation is successful.
VMamba: https://github.com/MzeroMiko/VMamba

**Comment by cyc1111111111** [comment]
> 此包属于 VMamba 环境，需要通读 VMamba 项目环境安装教程，确保其环境安装成功。 VMamba：https://github.com/MzeroMiko/VMamba

I am using a Windows environment and I would like to know if you are the same, if you can use the Windows environment to follow your operation successfully

**Comment by walking-shadow** [comment]
Sorry, we use the Linux environment and we recommend using the Linux environment to avoid some unexpected issues.

**Comment by deeplwrite** [comment]
我安装后也有这个问题
![Uploading e6404747feef0244053af4d18219e20.png…]()
